
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: meetingscheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      APP_ENV: development
      GIN_MODE: debug
      PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: meetingscheduler
      DB_SSLMODE: disable
      TZ: UTC
    ports:
      - "8080:8080"

volumes:
  postgres_data:
